#pragma once
/// @file quadrature.hpp
/// Gauss–Legendre and Gauss–Jacobi rules on [0,1] and collapsed (Duffy) Gauss–Jacobi rules on
/// the reference triangle and tetrahedron. Formulas: docs/theory/quadrature.md.
/// Rules of arbitrary order are generated by the Golub–Welsch algorithm, so there is no
/// upper limit on the degree; order ≥ 2p+1 is required for mass terms (CLAUDE.md §6).

#include <cstddef>
#include <vector>

#include "hpfem/core/types.hpp"

namespace hpfem::assembly {

/// Points and weights on the reference domain: the interval [0,1] for Dim = 1, the
/// reference triangle / tetrahedron of `fespace::ReferenceElement` otherwise.
template <int Dim>
struct QuadratureRule {
  std::vector<Point<Dim>> points;
  std::vector<Real> weights;  ///< sum to the measure of the reference domain
  int order = 0;              ///< polynomials of total degree ≤ order are integrated exactly

  [[nodiscard]] std::size_t size() const noexcept { return points.size(); }
};

/// Gauss–Legendre rule with n points on [0,1], exact to degree 2n − 1.
/// @throws InvalidArgument for n < 1.
[[nodiscard]] QuadratureRule<1> gauss_legendre(int n);

/// Gauss–Jacobi rule with n points on [0,1] for the weight @f$ (1-s)^\alpha s^\beta @f$,
/// @f$ \alpha, \beta > -1 @f$: @f$ \sum_j w_j g(s_j) = \int_0^1 g(s)(1-s)^\alpha s^\beta\,ds @f$
/// exactly for polynomials g of degree ≤ 2n − 1. The weight function is *not* part of the
/// returned weights' integrand, i.e. the rule is meant for integrands of the form
/// @f$ g(s)(1-s)^\alpha s^\beta @f$.
[[nodiscard]] QuadratureRule<1> gauss_jacobi(int n, Real alpha, Real beta);

/// Rule on the reference simplex exact for total degree ≤ `order` (≥ 0), built by collapsing
/// Gauss–Jacobi rules (n = ⌈(order+1)/2⌉ points per direction, n^Dim in total). All weights
/// are positive and all points lie strictly inside the simplex. For Dim = 1 this is
/// `gauss_legendre(n)`.
template <int Dim>
[[nodiscard]] QuadratureRule<Dim> simplex_quadrature(int order);

extern template QuadratureRule<1> simplex_quadrature<1>(int);
extern template QuadratureRule<2> simplex_quadrature<2>(int);
extern template QuadratureRule<3> simplex_quadrature<3>(int);

}  // namespace hpfem::assembly
